//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        public Grades()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int GradeId { get; set; }
        public string GradeName { get; set; }
        public string Section { get; set; }
    
        public virtual ICollection<Students> Students { get; set; }
    }
}
