//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<float> Weight { get; set; }
        public Nullable<int> GradeId { get; set; }
    
        public virtual Grades Grades { get; set; }
    }
}
